    """A collection of 4x5 letters of the alaphabet in beepers"""
    """All letters capital and have a space between them"""
    """Have ABCJHELLO"""
    def j(self):
        """Print J using beepers"""
        self.tl()
        self.m()
        self.put()
        self.ta()
        self.m()
        self.tl()
        self.m()
        self.put()
        self.m()
        self.tl()
        self.put5()
        self.tl()
        self.m()
        self.put()
        self.ta()
        self.m()
        self.m()
        self.put()
        self.tr()
        self.m()
        self.m()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.m()

    def a(self):
        """Print A using beepers"""
        self.tl()
        self.put2()
        self.m()
        self.put2()
        self.m()
        self.tr()
        self.m()
        self.put2()
        self.m()
        self.tr()
        self.m()
        self.put2()
        self.tr()
        self.m()
        self.put2()
        self.ta()
        self.m()
        self.m()
        self.tr()
        self.m()
        self.put2()
        self.tl()
        self.m()
        self.m()

    def c(self):
        """Print C using beepers"""
        self.tl()
        self.m()
        self.put2()
        self.m()
        self.put()
        self.m()
        self.tr()
        self.m()
        self.put2()
        self.m()
        self.put()
        self.ta()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.m()
        self.m()
        self.m()
        self.tl()
        self.put2()
        self.m()
        self.put()
        self.m()
        self.m()

    def o(self):
        """Print O using beepers"""
        self.tl()
        self.put5()
        self.ta()
        self.m()
        self.m()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.put2()
        self.m()
        self.tl()
        self.put5()
        self.tl()
        self.m()
        self.put2()
        self.tl()
        self.m()
        self.m()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.m()
        self.m()
        self.m()

    def b(self):
        """Print B using beepers"""
        self.tl()
        self.put5()
        self.tr()
        self.m()
        self.put2()
        self.tr()
        self.m()
        self.tl()
        """edited"""
        self.m()
        self.put()
        self.ta()
        self.m()
        self.tl()
        self.m()
        self.tr()
        self.put2()
        self.tl()
        self.m()
        self.m()
        self.tl()
        self.put2()
        self.m()
        self.tl()
        self.m()
        self.put()
        self.ta()
        self.m()
        self.tl()
        self.m()

    def h(self):
        """Print H using beepers"""
        self.tl()
        self.put5()
        self.tr()
        self.m()
        self.m()
        self.m()
        self.tr()
        self.put5()
        self.ta()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.put2()
        self.tl()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.m()
        self.m()
        self.m()

    def e(self):
        """Print E using beepers"""
        self.tl()
        self.put5()
        self.tr()
        self.m()
        self.put2()
        self.tr()
        self.m()
        self.m()
        self.tr()
        self.put2()
        self.tl()
        self.m()
        self.m()
        self.tl()
        self.put2()
        self.m()
        self.m()

    def l(self):
        """Print L using beepers"""
        self.tl()
        self.put5()
        self.ta()
        self.m()
        self.m()
        self.m()
        self.m()
        self.tl()
        self.m()
        self.put2()
        self.m()
        self.m()





